// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REPS_backend.Data;

#nullable disable

namespace REPS_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304020452_InitialMySql")]
    partial class InitialMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("REPS_backend.Models.Amistad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aceptada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaAmistad")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptorId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Amistades");
                });

            modelBuilder.Entity("REPS_backend.Models.DetalleMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionImpacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreMusculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.ToTable("DetallesMusculares");
                });

            modelBuilder.Entity("REPS_backend.Models.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionTecnica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoMuscular")
                        .HasColumnType("int");

                    b.Property<string>("ImagenMusculosUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("REPS_backend.Models.Entrenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("REPS_backend.Models.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IconoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("REPS_backend.Models.RecordPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRecord")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PesoAnterior")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PesoMaximo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.ToTable("RecordsPersonales");
                });

            modelBuilder.Entity("REPS_backend.Models.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Descargas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EsGeneradaPorIA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsPublica")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("REPS_backend.Models.RutinaEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DescansoSegundos")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<double>("PesoSugerido")
                        .HasColumnType("double");

                    b.Property<decimal>("PorcentajeDelPeso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Repeticiones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("REPS_backend.Models.SerieLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Completada")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int?>("EntrenamientoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoUsado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RepsRealizadas")
                        .HasColumnType("int");

                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("EntrenamientoId");

                    b.HasIndex("SesionId");

                    b.ToTable("SeriesLogs");
                });

            modelBuilder.Entity("REPS_backend.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DuracionRealMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EstaFinalizada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreRutinaSnapshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PuntosGanados")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("REPS_backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvatarId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoAmigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaBorrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaFinSuscripcion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActividad")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlanActual")
                        .HasColumnType("int");

                    b.Property<int>("PuntosLogros")
                        .HasColumnType("int");

                    b.Property<int>("PuntosRecords")
                        .HasColumnType("int");

                    b.Property<int>("PuntosTotales")
                        .HasColumnType("int");

                    b.Property<int>("RachaDias")
                        .HasColumnType("int");

                    b.Property<int>("RangoGeneral")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("REPS_backend.Models.UsuarioLogro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Desbloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaObtencion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LogroId")
                        .HasColumnType("int");

                    b.Property<double>("Progreso")
                        .HasColumnType("double");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogroId");

                    b.ToTable("UsuarioLogros");
                });

            modelBuilder.Entity("REPS_backend.Models.Amistad", b =>
                {
                    b.HasOne("REPS_backend.Models.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPS_backend.Models.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receptor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("REPS_backend.Models.DetalleMuscular", b =>
                {
                    b.HasOne("REPS_backend.Models.Ejercicio", null)
                        .WithMany("MusculosInvolucrados")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("REPS_backend.Models.Entrenamiento", b =>
                {
                    b.HasOne("REPS_backend.Models.Rutina", "Rutina")
                        .WithMany()
                        .HasForeignKey("RutinaId");

                    b.HasOne("REPS_backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("REPS_backend.Models.RecordPersonal", b =>
                {
                    b.HasOne("REPS_backend.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("REPS_backend.Models.Rutina", b =>
                {
                    b.HasOne("REPS_backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("REPS_backend.Models.RutinaEjercicio", b =>
                {
                    b.HasOne("REPS_backend.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPS_backend.Models.Rutina", null)
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("REPS_backend.Models.SerieLog", b =>
                {
                    b.HasOne("REPS_backend.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REPS_backend.Models.Entrenamiento", null)
                        .WithMany("SeriesRealizadas")
                        .HasForeignKey("EntrenamientoId");

                    b.HasOne("REPS_backend.Models.Sesion", null)
                        .WithMany("SeriesRealizadas")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("REPS_backend.Models.UsuarioLogro", b =>
                {
                    b.HasOne("REPS_backend.Models.Logro", "Logro")
                        .WithMany()
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");
                });

            modelBuilder.Entity("REPS_backend.Models.Ejercicio", b =>
                {
                    b.Navigation("MusculosInvolucrados");
                });

            modelBuilder.Entity("REPS_backend.Models.Entrenamiento", b =>
                {
                    b.Navigation("SeriesRealizadas");
                });

            modelBuilder.Entity("REPS_backend.Models.Rutina", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("REPS_backend.Models.Sesion", b =>
                {
                    b.Navigation("SeriesRealizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
